*Joaquin, Marc Christopher C.* <br>
*Engr. Dylan Lopez* <br>
*58010* 
# Linear Algebra for CpE
## Laboratory 7 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intemrediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [3]:
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [6]:
AT1 = np.transpose(A)

In [7]:
AT2 = A.T

In [11]:
np.array_equiv(AT1, AT2)

True

In [12]:
B = np.array([
    [1,2,3,4],
    [1,0,2,1],
])
B.shape

(2, 4)

In [13]:
np.transpose(B).shape

(4, 2)

In [14]:
B.T.shape

(4, 2)

#### Try to create your own matrix (you can try non-squares) to test transposition.

In [ ]:
## Try out your code here.

## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [15]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [16]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [17]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [18]:
X @ Y

array([[3, 4],
       [2, 2]])

In [19]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [20]:
A = np.array([
    [2, 4],
    [5, -2],
    [0, 1]
])
B = np.array([
    [1,1],
    [3,3],
    [-1,-2]
])
C = np.array([
    [0,1,1],
    [1,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [21]:
A @ C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [22]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [24]:
A @ B.T

array([[  6,  18, -10],
       [  3,   9,  -1],
       [  1,   3,  -2]])

In [27]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [30]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

And youcan see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

I'll be doing just one of the properties and I'll leave the rest to test your skills!

In [32]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,0]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [33]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.array_equal(a_dot_z,z_mat)

True

In [66]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [67]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [68]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [75]:
M = np.array([
    [1,7],
    [-3, 5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [77]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade


## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [2]:
A = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9],
])
B = np.array([
              [2,6,1],
              [4,3,5],
              [0,8,4],
])
C = np.array([
              [7,9,8],
              [1,6,5],
              [3,2,7],
])

 Property 1. $A \cdot B \neq B \cdot A$

In [23]:
#My function in A dot B
#first row of array 
ABzerobyzeroelement = ((A[0,0] * B[0,0])+(A[0,1] * B[1,0])+(A[0,2]*B[2,0]))
#print(ABzerobyzeroelement)
ABzerobyoneelement = ((A[0,0] * B[0,1])+(A[0,1] * B[1,1])+(A[0,2]*B[2,1]))
#print(ABzerobyoneelement)
ABzerobytwoelement = ((A[0,0] * B[0,2])+(A[0,1] * B[1,2])+(A[0,2]*B[2,2]))
#print(ABzerobytwoelement)

#second row of array 
ABonebyzeroelement = ((A[1,0] * B[0,0])+(A[1,1] * B[1,0])+(A[1,2]*B[2,0]))
#print(ABonebyzeroelement)
ABonebyoneelement = ((A[1,0] * B[0,1])+(A[1,1] * B[1,1])+(A[1,2]*B[2,1]))
#print(ABonebyoneelement)
ABonebytwoelement = ((A[1,0] * B[0,2])+(A[1,1] * B[1,2])+(A[1,2]*B[2,2]))
#print(ABonebytwoelement)

#third row of array
ABtwobyzeroelement = ((A[2,0] * B[0,0])+(A[2,1] * B[1,0])+(A[2,2]*B[2,0]))
#print(ABtwobyzeroelement)
ABtwobyoneelement = ((A[2,0] * B[0,1])+(A[2,1] * B[1,1])+(A[2,2]*B[2,1]))
#print(ABtwobyoneelement)
ABtwobytwoelement = ((A[2,0] * B[0,2])+(A[2,1] * B[1,2])+(A[2,2]*B[2,2]))
#print(ABtwobytwoelement)

print(f'The product of A and B are:\n [{[ABzerobyzeroelement, ABzerobyoneelement, ABzerobytwoelement]},\n {[ABonebyzeroelement, ABonebyoneelement, ABonebytwoelement]},\n {[ABtwobyzeroelement, ABtwobyoneelement, ABtwobytwoelement]}]')



23
The product of A and B are:
 [[10, 36, 23],
 [28, 87, 53],
 [46, 138, 83]]


In [4]:
np.dot(A,B)

array([[ 10,  36,  23],
       [ 28,  87,  53],
       [ 46, 138,  83]])

In [34]:
#My function in B dot A
#first row of array 
BAzerobyzeroelement = ((B[0,0] * A[0,0])+(B[0,1] * A[1,0])+(B[0,2]*A[2,0]))
#print(BAzerobyzeroelement)
BAzerobyoneelement = ((B[0,0] * A[0,1])+(B[0,1] * A[1,1])+(B[0,2]*A[2,1]))
#print(BAzerobyoneelement)
BAzerobytwoelement = ((B[0,0] * A[0,2])+(B[0,1] * A[1,2])+(B[0,2]*A[2,2]))
#print(BAzerobytwoelement)

#second row of array 
BAonebyzeroelement = ((B[1,0] * A[0,0])+(B[1,1] * A[1,0])+(B[1,2]*A[2,0]))
#print(BAonebyzeroelement)
BAonebyoneelement = ((B[1,0] * A[0,1])+(B[1,1] * A[1,1])+(B[1,2]*A[2,1]))
#print(BAonebyoneelement)
BAonebytwoelement = ((B[1,0] * A[0,2])+(B[1,1] * A[1,2])+(B[1,2]*A[2,2]))
#print(BAonebytwoelement)

#third row of array
BAtwobyzeroelement = ((B[2,0] * A[0,0])+(B[2,1] * A[1,0])+(B[2,2]*A[2,0]))
#print(BAtwobyzeroelement)
BAtwobyoneelement = ((B[2,0] * A[0,1])+(B[2,1] * A[1,1])+(B[2,2]*A[2,1]))
#print(BAtwobyoneelement)
BAtwobytwoelement = ((B[2,0] * A[0,2])+(B[2,1] * A[1,2])+(B[2,2]*A[2,2]))
#print(BAtwobytwoelement)

print(f'The product of B and A are:\n [{[BAzerobyzeroelement, BAzerobyoneelement, BAzerobytwoelement]},\n {[BAonebyzeroelement, BAonebyoneelement, BAonebytwoelement]},\n {[BAtwobyzeroelement, BAtwobyoneelement, BAtwobytwoelement]}]')



The product of B and A are:
 [[33, 42, 51],
 [51, 63, 75],
 [60, 72, 84]]


In [6]:
np.dot(B,A)

array([[33, 42, 51],
       [51, 63, 75],
       [60, 72, 84]])

In [7]:
np.dot(A,B) == np.dot(B,A)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

Property 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [40]:
#My function in A dot (B dot C)
#first row of array 
BCAzerobyzeroelement = ((ABzerobyzeroelement * C[0,0])+(ABzerobyoneelement * C[1,0])+(ABzerobytwoelement *C[2,0]))
#print(BCAzerobyzeroelement)
BCAzerobyoneelement = ((ABzerobyzeroelement * C[0,1])+(ABzerobyoneelement * C[1,1])+(ABzerobytwoelement*C[2,1]))
#print(BCAzerobyoneelement)
BCAzerobytwoelement = ((ABzerobyzeroelement * C[0,2])+(ABzerobyoneelement * C[1,2])+(ABzerobytwoelement*C[2,2]))
#print(BCAzerobytwoelement)

#second row of array 
BCAonebyzeroelement = ((ABonebyzeroelement * C[0,0])+(ABonebyoneelement * C[1,0])+(ABonebytwoelement*C[2,0]))
#print(BCAonebyzeroelement)
BCAonebyoneelement = ((ABonebyzeroelement * C[0,1])+(ABonebyoneelement * C[1,1])+(ABonebytwoelement*C[2,1]))
#print(BCAonebyoneelement)
BCAonebytwoelement = ((ABonebyzeroelement * C[0,2])+(ABonebyoneelement * C[1,2])+(ABonebytwoelement*C[2,2]))
#print(BCAonebytwoelement)

#third row of array
BCAtwobyzeroelement = ((ABtwobyzeroelement * C[0,0])+(ABtwobyoneelement * C[1,0])+(ABtwobytwoelement*C[2,0]))
#print(BCAtwobyzeroelement)
BCAtwobyoneelement = ((ABtwobyzeroelement * C[0,1])+(ABtwobyoneelement * C[1,1])+(ABtwobytwoelement*C[2,1]))
#print(BCAtwobyoneelement)
BCAtwobytwoelement = ((ABtwobyzeroelement * C[0,2])+(ABtwobyoneelement * C[1,2])+(ABtwobytwoelement*C[2,2]))
#print(BCAtwobytwoelement)

print(f'The product of A and B are:\n [{[BCAzerobyzeroelement, BCAzerobyoneelement, BCAzerobytwoelement]},\n {[BCAonebyzeroelement, BCAonebyoneelement, BCAonebytwoelement]},\n {[BCAtwobyzeroelement, BCAtwobyoneelement, BCAtwobytwoelement]}]')




The product of A and B are:
 [[175, 352, 421],
 [442, 880, 1030],
 [709, 1408, 1639]]


In [35]:
A @ (B @ C)

array([[ 175,  352,  421],
       [ 442,  880, 1030],
       [ 709, 1408, 1639]])

In [29]:
#My function in (A dot B) dot C
#first row of array 
ABCzerobyzeroelement = ((ABzerobyzeroelement * C[0,0])+(ABzerobyoneelement * C[1,0])+(ABzerobytwoelement *C[2,0]))
#print(ABzerobyzeroelement)
ABCzerobyoneelement = ((ABzerobyzeroelement * C[0,1])+(ABzerobyoneelement * C[1,1])+(ABzerobytwoelement*C[2,1]))
#print(ABzerobyoneelement)
ABCzerobytwoelement = ((ABzerobyzeroelement * C[0,2])+(ABzerobyoneelement * C[1,2])+(ABzerobytwoelement*C[2,2]))
#print(ABzerobytwoelement)

#second row of array 
ABConebyzeroelement = ((ABonebyzeroelement * C[0,0])+(ABonebyoneelement * C[1,0])+(ABonebytwoelement*C[2,0]))
#print(ABonebyzeroelement)
ABConebyoneelement = ((ABonebyzeroelement * C[0,1])+(ABonebyoneelement * C[1,1])+(ABonebytwoelement*C[2,1]))
#print(ABonebyoneelement)
ABConebytwoelement = ((ABonebyzeroelement * C[0,2])+(ABonebyoneelement * C[1,2])+(ABonebytwoelement*C[2,2]))
#print(ABonebytwoelement)

#third row of array
ABCtwobyzeroelement = ((ABtwobyzeroelement * C[0,0])+(ABtwobyoneelement * C[1,0])+(ABtwobytwoelement*C[2,0]))
#print(ABtwobyzeroelement)
ABCtwobyoneelement = ((ABtwobyzeroelement * C[0,1])+(ABtwobyoneelement * C[1,1])+(ABtwobytwoelement*C[2,1]))
#print(ABtwobyoneelement)
ABCtwobytwoelement = ((ABtwobyzeroelement * C[0,2])+(ABtwobyoneelement * C[1,2])+(ABtwobytwoelement*C[2,2]))
#print(ABtwobytwoelement)

print(f'The product of A and B are:\n [{[ABCzerobyzeroelement, ABCzerobyoneelement, ABCzerobytwoelement]},\n {[ABConebyzeroelement, ABConebyoneelement, ABConebytwoelement]},\n {[ABCtwobyzeroelement, ABCtwobyoneelement, ABCtwobytwoelement]}]')



The product of A and B are:
 [[175, 352, 421],
 [442, 880, 1030],
 [709, 1408, 1639]]


In [36]:
(A @ B) @ C

array([[ 175,  352,  421],
       [ 442,  880, 1030],
       [ 709, 1408, 1639]])

In [9]:
A @ (B @ C) == (A @ B) @ C

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Property 3. $A\cdot(B+C) = A\cdot B + A\cdot C$

In [47]:
#For A at (B plus C)
#add B and C 
E = B+C
print(f'The sum of B and C are:\n{E}')
#A at BC
#first row of array 
AEzerobyzeroelement = ((A[0,0] * E[0,0])+(A[0,1] * E[1,0])+(A[0,2]*E[2,0]))
#print(AEzerobyzeroelement)
AEzerobyoneelement = ((A[0,0] * E[0,1])+(A[0,1] * E[1,1])+(A[0,2]*E[2,1]))
#print(AEzerobyoneelement)
AEzerobytwoelement = ((A[0,0] * E[0,2])+(A[0,1] * E[1,2])+(A[0,2]*E[2,2]))
#print(AEzerobytwoelement)

#second row of array 
AEonebyzeroelement = ((A[1,0] * E[0,0])+(A[1,1] * E[1,0])+(A[1,2]*E[2,0]))
#print(AEonebyzeroelement)
AEonebyoneelement = ((A[1,0] * E[0,1])+(A[1,1] * E[1,1])+(A[1,2]*E[2,1]))
#print(AEonebyoneelement)
AEonebytwoelement = ((A[1,0] * E[0,2])+(A[1,1] * E[1,2])+(A[1,2]*E[2,2]))
#print(AEonebytwoelement)

#third row of array
AEtwobyzeroelement = ((A[2,0] * E[0,0])+(A[2,1] * E[1,0])+(A[2,2]*E[2,0]))
#print(AEtwobyzeroelement)
AEtwobyoneelement = ((A[2,0] * E[0,1])+(A[2,1] * E[1,1])+(A[2,2]*E[2,1]))
#print(AEtwobyoneelement)
AEtwobytwoelement = ((A[2,0] * E[0,2])+(A[2,1] * E[1,2])+(A[2,2]*E[2,2]))
#print(AEtwobytwoelement)

print(f'The product of A and E are:\n [{[AEzerobyzeroelement, AEzerobyoneelement, AEzerobytwoelement]},\n {[AEonebyzeroelement, AEonebyoneelement, AEonebytwoelement]},\n {[AEtwobyzeroelement, AEtwobyoneelement, AEtwobytwoelement]}]')



The sum of B and C are:
[[ 9 15  9]
 [ 5  9 10]
 [ 3 10 11]]
The product of A and E are:
 [[28, 63, 62],
 [79, 165, 152],
 [130, 267, 242]]


In [10]:
A @ (B+C)

array([[ 28,  63,  62],
       [ 79, 165, 152],
       [130, 267, 242]])

In [49]:
#For the product of A and B add to the product of A and C 
#Product of A and B 
#first row of array 
ABzerobyzeroelement = ((A[0,0] * B[0,0])+(A[0,1] * B[1,0])+(A[0,2]*B[2,0]))
#print(ABzerobyzeroelement)
ABzerobyoneelement = ((A[0,0] * B[0,1])+(A[0,1] * B[1,1])+(A[0,2]*B[2,1]))
#print(ABzerobyoneelement)
ABzerobytwoelement = ((A[0,0] * B[0,2])+(A[0,1] * B[1,2])+(A[0,2]*B[2,2]))
#print(ABzerobytwoelement)

#second row of array 
ABonebyzeroelement = ((A[1,0] * B[0,0])+(A[1,1] * B[1,0])+(A[1,2]*B[2,0]))
#print(ABonebyzeroelement)
ABonebyoneelement = ((A[1,0] * B[0,1])+(A[1,1] * B[1,1])+(A[1,2]*B[2,1]))
#print(ABonebyoneelement)
ABonebytwoelement = ((A[1,0] * B[0,2])+(A[1,1] * B[1,2])+(A[1,2]*B[2,2]))
#print(ABonebytwoelement)

#third row of array
ABtwobyzeroelement = ((A[2,0] * B[0,0])+(A[2,1] * B[1,0])+(A[2,2]*B[2,0]))
#print(ABtwobyzeroelement)
ABtwobyoneelement = ((A[2,0] * B[0,1])+(A[2,1] * B[1,1])+(A[2,2]*B[2,1]))
#print(ABtwobyoneelement)
ABtwobytwoelement = ((A[2,0] * B[0,2])+(A[2,1] * B[1,2])+(A[2,2]*B[2,2]))
#print(ABtwobytwoelement)

print(f'The product of A and B are:\n [{[ABzerobyzeroelement, ABzerobyoneelement, ABzerobytwoelement]},\n {[ABonebyzeroelement, ABonebyoneelement, ABonebytwoelement]},\n {[ABtwobyzeroelement, ABtwobyoneelement, ABtwobytwoelement]}]')

#Product of A and C
#first row of array 
ACzerobyzeroelement = ((A[0,0] * C[0,0])+(A[0,1] * C[1,0])+(A[0,2]*C[2,0]))
#print(ACzerobyzeroelement)
ACzerobyoneelement = ((A[0,0] * C[0,1])+(A[0,1] * C[1,1])+(A[0,2]*C[2,1]))
#print(ACzerobyoneelement)
ACzerobytwoelement = ((A[0,0] * C[0,2])+(A[0,1] * C[1,2])+(A[0,2]*C[2,2]))
#print(ACzerobytwoelement)

#second row of array 
AConebyzeroelement = ((A[1,0] * C[0,0])+(A[1,1] * C[1,0])+(A[1,2]*C[2,0]))
#print(AConebyzeroelement)
AConebyoneelement = ((A[1,0] * C[0,1])+(A[1,1] * C[1,1])+(A[1,2]*C[2,1]))
#print(AConebyoneelement)
AConebytwoelement = ((A[1,0] * C[0,2])+(A[1,1] * C[1,2])+(A[1,2]*C[2,2]))
#print(AConebytwoelement)

#third row of array
ACtwobyzeroelement = ((A[2,0] * C[0,0])+(A[2,1] * C[1,0])+(A[2,2]*C[2,0]))
#print(ACtwobyzeroelement)
ACtwobyoneelement = ((A[2,0] * C[0,1])+(A[2,1] * C[1,1])+(A[2,2]*C[2,1]))
#print(ACtwobyoneelement)
ACtwobytwoelement = ((A[2,0] * C[0,2])+(A[2,1] * C[1,2])+(A[2,2]*C[2,2]))
#print(ACtwobytwoelement)

print(f'The product of A and C are:\n [{[ACzerobyzeroelement, ACzerobyoneelement, ACzerobytwoelement]},\n {[AConebyzeroelement, AConebyoneelement, AConebytwoelement]},\n {[ACtwobyzeroelement, ACtwobyoneelement, ACtwobytwoelement]}]')

#For the sum
SUMone = ABzerobyzeroelement + ACzerobyzeroelement
SUMtwo = ABzerobyoneelement + ACzerobyoneelement
SUMthree = ABzerobytwoelement + ACzerobytwoelement
SUMfour = ABonebyzeroelement + AConebyzeroelement
SUMfive = ABonebyoneelement + AConebyoneelement
SUMsix = ABonebytwoelement + AConebytwoelement
SUMseven = ABtwobyzeroelement + ACtwobyzeroelement
SUMeight = ABtwobyoneelement + ACtwobyoneelement
SUMnine = ABtwobyoneelement + ACtwobytwoelement

print(f'Overall are:\n [{[SUMone, SUMtwo, SUMthree]},\n {[SUMfour, SUMfive, SUMsix]},\n {[SUMseven, SUMeight, SUMnine]}]')

The product of A and B are:
 [[10, 36, 23],
 [28, 87, 53],
 [46, 138, 83]]
The product of A and C are:
 [[18, 27, 39],
 [51, 78, 99],
 [84, 129, 159]]
Overall are:
 [[28, 63, 62],
 [79, 165, 152],
 [130, 267, 297]]


In [11]:
A@B + A@C

array([[ 28,  63,  62],
       [ 79, 165, 152],
       [130, 267, 242]])

In [13]:
(A @ (B+C)) == (A@B + A@C)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Property 4. $(B+C)\cdot A = B\cdot A + C\cdot A$

In [52]:
#Add B and C 
Z = B+C
print(f'The sum of B and C are:\n{E}')

#Z at A
#first row of array 
ZAzerobyzeroelement = ((Z[0,0] * A[0,0])+(Z[0,1] * A[1,0])+(Z[0,2]*A[2,0]))
#print(ZAzerobyzeroelement)
ZAzerobyoneelement = ((Z[0,0] * A[0,1])+(Z[0,1] * A[1,1])+(Z[0,2]*A[2,1]))
#print(ZAzerobyoneelement)
ZAzerobytwoelement = ((Z[0,0] * A[0,2])+(Z[0,1] * A[1,2])+(Z[0,2]*A[2,2]))
#print(ZAzerobytwoelement)

#second row of array 
ZAonebyzeroelement = ((Z[1,0] * A[0,0])+(Z[1,1] * A[1,0])+(Z[1,2]*A[2,0]))
#print(ZAonebyzeroelement)
ZAonebyoneelement = ((Z[1,0] * A[0,1])+(Z[1,1] * A[1,1])+(Z[1,2]*A[2,1]))
#print(ZAonebyoneelement)
ZAonebytwoelement = ((Z[1,0] * A[0,2])+(Z[1,1] * A[1,2])+(Z[1,2]*A[2,2]))
#print(ZAonebytwoelement)

#third row of array
ZAtwobyzeroelement = ((Z[2,0] * A[0,0])+(Z[2,1] * A[1,0])+(Z[2,2]*A[2,0]))
#print(ZAtwobyzeroelement)
ZAtwobyoneelement = ((Z[2,0] * A[0,1])+(Z[2,1] * A[1,1])+(Z[2,2]*A[2,1]))
#print(ZAtwobyoneelement)
ZAtwobytwoelement = ((Z[2,0] * A[0,2])+(Z[2,1] * A[1,2])+(Z[2,2]*A[2,2]))
#print(ZAtwobytwoelement)

print(f'The product of Z and A are:\n [{[ZAzerobyzeroelement, ZAzerobyoneelement, ZAzerobytwoelement]},\n {[ZAonebyzeroelement, ZAonebyoneelement, ZAonebytwoelement]},\n {[ZAtwobyzeroelement, ZAtwobyoneelement, ZAtwobytwoelement]}]')




The sum of B and C are:
[[ 9 15  9]
 [ 5  9 10]
 [ 3 10 11]]
The product of Z and A are:
 [[132, 165, 198],
 [111, 135, 159],
 [120, 144, 168]]


In [14]:
(B+C) @ A 

array([[132, 165, 198],
       [111, 135, 159],
       [120, 144, 168]])

In [53]:
#For the product of B and A add to the product of C and A 
#Product of B and A 
#first row of array 
BAzerobyzeroelement = ((B[0,0] * A[0,0])+(B[0,1] * A[1,0])+(B[0,2]*A[2,0]))
#print(BAzerobyzeroelement)
BAzerobyoneelement = ((B[0,0] * A[0,1])+(B[0,1] * A[1,1])+(B[0,2]*A[2,1]))
#print(BAzerobyoneelement)
BAzerobytwoelement = ((B[0,0] * A[0,2])+(B[0,1] * A[1,2])+(B[0,2]*A[2,2]))
#print(BAzerobytwoelement)

#second row of array 
BAonebyzeroelement = ((B[1,0] * A[0,0])+(B[1,1] * A[1,0])+(B[1,2]*A[2,0]))
#print(BAonebyzeroelement)
BAonebyoneelement = ((B[1,0] * A[0,1])+(B[1,1] * A[1,1])+(B[1,2]*A[2,1]))
#print(BAonebyoneelement)
BAonebytwoelement = ((B[1,0] * A[0,2])+(B[1,1] * A[1,2])+(B[1,2]*A[2,2]))
#print(BAonebytwoelement)

#third row of array
BAtwobyzeroelement = ((B[2,0] * A[0,0])+(B[2,1] * A[1,0])+(B[2,2]*A[2,0]))
#print(BAtwobyzeroelement)
BAtwobyoneelement = ((B[2,0] * A[0,1])+(B[2,1] * A[1,1])+(B[2,2]*A[2,1]))
#print(BAtwobyoneelement)
BAtwobytwoelement = ((B[2,0] * A[0,2])+(B[2,1] * A[1,2])+(B[2,2]*A[2,2]))
#print(BAtwobytwoelement)

print(f'The product of B and A are:\n [{[BAzerobyzeroelement, BAzerobyoneelement, BAzerobytwoelement]},\n {[BAonebyzeroelement, BAonebyoneelement, BAonebytwoelement]},\n {[BAtwobyzeroelement, BAtwobyoneelement, BAtwobytwoelement]}]')

#Product of C and A
#first row of array 
CAzerobyzeroelement = ((C[0,0] * A[0,0])+(C[0,1] * A[1,0])+(C[0,2]*A[2,0]))
#print(CAzerobyzeroelement)
CAzerobyoneelement = ((C[0,0] * A[0,1])+(C[0,1] * A[1,1])+(C[0,2]*A[2,1]))
#print(CAzerobyoneelement)
CAzerobytwoelement = ((C[0,0] * A[0,2])+(C[0,1] * A[1,2])+(C[0,2]*A[2,2]))
#print(CAzerobytwoelement)

#second row of array 
CAonebyzeroelement = ((C[1,0] * A[0,0])+(C[1,1] * A[1,0])+(C[1,2]*A[2,0]))
#print(CAonebyzeroelement)
CAonebyoneelement = ((C[1,0] * A[0,1])+(C[1,1] * A[1,1])+(C[1,2]*A[2,1]))
#print(CAonebyoneelement)
CAonebytwoelement = ((C[1,0] * A[0,2])+(C[1,1] * A[1,2])+(C[1,2]*A[2,2]))
#print(CAonebytwoelement)

#third row of array
CAtwobyzeroelement = ((C[2,0] * A[0,0])+(C[2,1] * A[1,0])+(C[2,2]*A[2,0]))
#print(CAtwobyzeroelement)
CAtwobyoneelement = ((C[2,0] * A[0,1])+(C[2,1] * A[1,1])+(C[2,2]*A[2,1]))
#print(CAtwobyoneelement)
CAtwobytwoelement = ((C[2,0] * A[0,2])+(C[2,1] * A[1,2])+(C[2,2]*A[2,2]))
#print(CAtwobytwoelement)

print(f'The product of C and A are:\n [{[CAzerobyzeroelement, CAzerobyoneelement, CAzerobytwoelement]},\n {[CAonebyzeroelement, CAonebyoneelement, CAonebytwoelement]},\n {[CAtwobyzeroelement, CAtwobyoneelement, CAtwobytwoelement]}]')

#For the sum
sumone = BAzerobyzeroelement + CAzerobyzeroelement
sumtwo = BAzerobyoneelement + CAzerobyoneelement
sumthree = BAzerobytwoelement + CAzerobytwoelement
sumfour = BAonebyzeroelement + CAonebyzeroelement
sumfive = BAonebyoneelement + CAonebyoneelement
sumsix = BAonebytwoelement + CAonebytwoelement
sumseven = BAtwobyzeroelement + CAtwobyzeroelement
sumeight = BAtwobyoneelement + CAtwobyoneelement
sumnine = BAtwobyoneelement + CAtwobytwoelement

print(f'Overall are:\n [{[sumone, sumtwo, sumthree]},\n {[sumfour, sumfive, sumsix]},\n {[sumseven, sumeight, sumnine]}]')

The product of B and A are:
 [[33, 42, 51],
 [51, 63, 75],
 [60, 72, 84]]
The product of C and A are:
 [[99, 123, 147],
 [60, 72, 84],
 [60, 72, 84]]
Overall are:
 [[132, 165, 198],
 [111, 135, 159],
 [120, 144, 156]]


In [15]:
B@A + C@A

array([[132, 165, 198],
       [111, 135, 159],
       [120, 144, 168]])

In [16]:
(B+C) @ A  == B@A + C@A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Property 5. $A\cdot I = A$

In [17]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
#For A at I
O = np.eye(3)
O

#A at O
#first row of array 
AOzerobyzeroelement = ((A[0,0] * O[0,0])+(A[0,1] * O[1,0])+(A[0,2]*O[2,0]))
#print(AOzerobyzeroelement)
AOzerobyoneelement = ((A[0,0] * O[0,1])+(A[0,1] * O[1,1])+(A[0,2]*O[2,1]))
#print(AOzerobyoneelement)
AOzerobytwoelement = ((A[0,0] * O[0,2])+(A[0,1] * O[1,2])+(A[0,2]*O[2,2]))
#print(AOzerobytwoelement)

#second row of array 
AOonebyzeroelement = ((A[1,0] * O[0,0])+(A[1,1] * O[1,0])+(A[1,2]*O[2,0]))
#print(AOonebyzeroelement)
AOonebyoneelement = ((A[1,0] * O[0,1])+(A[1,1] * O[1,1])+(A[1,2]*O[2,1]))
#print(AOonebyoneelement)
AOonebytwoelement = ((A[1,0] * O[0,2])+(A[1,1] * O[1,2])+(A[1,2]*O[2,2]))
#print(AOonebytwoelement)

#third row of array
AOtwobyzeroelement = ((A[2,0] * O[0,0])+(A[2,1] * O[1,0])+(A[2,2]*O[2,0]))
#print(AOtwobyzeroelement)
AOtwobyoneelement = ((A[2,0] * O[0,1])+(A[2,1] * O[1,1])+(A[2,2]*O[2,1]))
#print(AOtwobyoneelement)
AOtwobytwoelement = ((A[2,0] * O[0,2])+(A[2,1] * O[1,2])+(A[2,2]*O[2,2]))
#print(AOtwobytwoelement)

print(f'The product of A and I are:\n [{[AOzerobyzeroelement, AOzerobyoneelement, AOzerobytwoelement]},\n {[AOonebyzeroelement, AOonebyoneelement, AOonebytwoelement]},\n {[AOtwobyzeroelement, AOtwobyoneelement, AOtwobytwoelement]}]')



The product of A and I are:
 [[1.0, 2.0, 3.0],
 [4.0, 5.0, 6.0],
 [7.0, 8.0, 9.0]]


In [19]:
A @ np.eye(3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [20]:
A @ np.eye(3) == A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Property 6. $C\cdot \emptyset = \emptyset$

In [59]:
null_mat = np.zeros((3,3))
print(null_mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [60]:
#For C at Null

#first row of array 
Cnullzerobyzeroelement = ((C[0,0] * null_mat[0,0])+(C[0,1] * null_mat[1,0])+(C[0,2]*null_mat[2,0]))
#print(Cnullzerobyzeroelement)
Cnullzerobyoneelement = ((C[0,0] * null_mat[0,1])+(C[0,1] * null_mat[1,1])+(C[0,2]*null_mat[2,1]))
#print(Cnullzerobyoneelement)
Cnullzerobytwoelement = ((C[0,0] * null_mat[0,2])+(C[0,1] * null_mat[1,2])+(C[0,2]*null_mat[2,2]))
#print(Cnullzerobytwoelement)

#second row of array 
Cnullonebyzeroelement = ((C[1,0] * null_mat[0,0])+(C[1,1] * null_mat[1,0])+(C[1,2]*null_mat[2,0]))
#print(Cnullonebyzeroelement)
Cnullonebyoneelement = ((C[1,0] * null_mat[0,1])+(C[1,1] * null_mat[1,1])+(C[1,2]*null_mat[2,1]))
#print(Cnullonebyoneelement)
Cnullonebytwoelement = ((C[1,0] * null_mat[0,2])+(C[1,1] * null_mat[1,2])+(C[1,2]*null_mat[2,2]))
#print(Cnullonebytwoelement)

#third row of array
Cnulltwobyzeroelement = ((C[2,0] * null_mat[0,0])+(C[2,1] * null_mat[1,0])+(C[2,2]*null_mat[2,0]))
#print(Cnulltwobyzeroelement)
Cnulltwobyoneelement = ((C[2,0] * null_mat[0,1])+(C[2,1] * null_mat[1,1])+(C[2,2]*null_mat[2,1]))
#print(Cnulltwobyoneelement)
Cnulltwobytwoelement = ((C[2,0] * null_mat[0,2])+(C[2,1] * null_mat[1,2])+(C[2,2]*null_mat[2,2]))
#print(Cnulltwobytwoelement)

print(f'The product of C and Null are:\n [{[Cnullzerobyzeroelement, Cnullzerobyoneelement, Cnullzerobytwoelement]},\n {[Cnullonebyzeroelement, Cnullonebyoneelement, Cnullonebytwoelement]},\n {[Cnulltwobyzeroelement, Cnulltwobyoneelement, Cnulltwobytwoelement]}]')



The product of C and Null are:
 [[0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0]]


In [23]:
C @ null_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
C @ null_mat == null_mat

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "how can matrix operations solve problems in healthcare?". 

On the given activities, I learned how to used operations, multiplication to be exact, by means of using codes. It is much easier than computing manually. I achieved the same precise values every time I tried to compute different values in a specific array. Moreover, it is not time consuming even though, I am computing several data and I can conclude that it can be more easier accurate and efficient to use programming for computation compare to manually type every value in the calculator. Nonetheless, this matrix operations solve problems in healthcare so we can compute the cases here in the Philippines if it increases or decreases. With this matrix operation, it can help to compute a tons of datas of the healthcare so that our healthcare facility won't consume their time too much to count the numbers of patients, cases and many more.